# Generated by Django 6.1.1 on 2026-09-22 13:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('estudando', 'Estudando'), ('completo', 'Completo'), ('revisado', 'Revisado')], db_index=True, default='pendente', max_length=20)),
                ('estudado_em', models.DateTimeField(blank=True, null=True)),
                ('proxima_revisao', models.DateField(blank=True, db_index=True, null=True)),
                ('intervalo_dias', models.PositiveIntegerField(default=0)),
                ('total_acertos', models.PositiveIntegerField(default=0)),
                ('total_erros', models.PositiveIntegerField(default=0)),
                ('minutos_estudados', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='estudos.disciplina')),
            ],
            options={
                'ordering': ['disciplina__ordem', 'ordem', 'id'],
                'unique_together': {('disciplina', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='SessaoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('segundos_liquidos', models.PositiveIntegerField(default=0)),
                ('acertos', models.PositiveIntegerField(default=0)),
                ('erros', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='estudos.disciplina')),
                ('topico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='estudos.topico')),
            ],
            options={
                'ordering': ['-iniciada_em'],
            },
        ),
    ]
