# Generated by Django 6.1.1 on 2026-09-22 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_por_dia', models.PositiveIntegerField(default=120, help_text='Horas líquidas diárias em minutos (ex.: 120 = 2h)')),
                ('dias_estudo', models.JSONField(default=list)),
                ('minutos_padrao_topico', models.PositiveIntegerField(default=40, help_text='Estimativa padrão por aula (vídeo + questões), em minutos')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('modo_distribuicao', models.CharField(choices=[('intercalar', 'Intercalar disciplinas'), ('sequencial', 'Ordem do edital')], default='intercalar', max_length=20)),
                ('gerado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano de estudo',
                'verbose_name_plural': 'Plano de estudo',
            },
        ),
        migrations.AddField(
            model_name='topico',
            name='minutos_estimados',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.CreateModel(
            name='ItemCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('minutos_planejados', models.PositiveIntegerField(default=40)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('concluido', models.BooleanField(default=False)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_cronograma', to='estudos.topico')),
            ],
            options={
                'ordering': ['data', 'ordem', 'id'],
                'unique_together': {('data', 'topico')},
            },
        ),
    ]
