# Generated by Django 6.1.1 on 2026-09-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0002_planoestudo_topico_minutos_estimados_itemcronograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoestudo',
            name='minutos_extra_questoes',
            field=models.PositiveIntegerField(default=15, help_text='Minutos extras por aula para resolver questões'),
        ),
        migrations.AddField(
            model_name='topico',
            name='minutos_video',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planoestudo',
            name='minutos_padrao_topico',
            field=models.PositiveIntegerField(default=40, help_text='Fallback quando a aula não tem duração do vídeo'),
        ),
    ]
