# Generated by Django 6.1.1 on 2026-09-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0004_planoestudo_data_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['peso', 'ordem', 'nome']},
        ),
        migrations.AddField(
            model_name='disciplina',
            name='peso',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='planoestudo',
            name='incluir_tempo_questoes',
            field=models.BooleanField(default=True, help_text='Se desmarcado, o cronograma usa só a duração do vídeo'),
        ),
        migrations.AlterField(
            model_name='planoestudo',
            name='modo_distribuicao',
            field=models.CharField(choices=[('intercalar', 'Intercalar disciplinas'), ('sequencial', 'Ordem do edital'), ('prioridade', 'Prioridade na prova (Bancários, Mat. Fin., Port.)')], default='prioridade', max_length=20),
        ),
    ]
